services:
  database:
    image: postgres
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pgdata
    ports:
      - 5432:5432
    volumes:
      - data:/data/pgdata
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run test

    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file: ./backend/.env

volumes:
  data:
